Selected tag is not shown when isMutliple is false
silverstripe-labs/silverstripe-tagfield pull request #201
Opened 2021-12-18 23:10 UTC by wilr

Fixes 195, 153

2022-02-01 23:04 UTC, emteknetnz requested changes
Looks good so far, I've left feedback and there's also a travis unit test failure to sort out too. I haven't manually replicated issue or tested PR yet.

2022-02-01 23:04 UTC, emteknetnz commented on client/src/components/TagField.js
> +    console.log(this.props);
```suggestion
```

2022-02-01 23:04 UTC, emteknetnz commented on src/TagField.php
> -    public function setValue($value, $source = null)
This is backwards incompatible API change, we cannot remove this public function

2022-02-01 23:04 UTC, emteknetnz commented on src/TagField.php
> +        return [trim($values)];
```suggestion
        return [trim((string) $values)];
```
?

2022-02-01 23:04 UTC, emteknetnz commented on src/TagField.php
> +    protected function getListValues($values)
```suggestion
    protected function getListValues($values): array
```

2022-02-01 23:04 UTC, emteknetnz commented on client/src/components/TagField.js
> +import React, { Component } from "react";
There's a lot of JS changes that look like your IDE may have done some automated formatting.  Double quotes are not standard in this codebase, so these change will need to be reverted. It's causing linting errors in travis - https://app.travis-ci.com/github/silverstripe/silverstripe-tagfield/jobs/552813829

2022-02-01 23:04 UTC, emteknetnz commented on readme.md
> +[![Build
These long lines weren't failing any existing linting rules, and now won't match other modules. Please revert

2022-02-01 23:04 UTC, emteknetnz commented on src/TagField.php
> +    public function getSchemaDataType()
```suggestion
    public function getSchemaDataType(): string
```

2022-02-01 23:04 UTC, emteknetnz commented on src/TagField.php
> +            $value = isset($value['Value']) ? $value['Value'] : '';
```suggestion
            $value = $value['Value'] ?? '';
```

2022-02-01 23:04 UTC, emteknetnz commented on src/TagField.php
> +        }
```suggestion
        if ($this->getIsMultiple()) {
            return self::SCHEMA_DATA_TYPE_MULTISELECT;
        }
        return self::SCHEMA_DATA_TYPE_SINGLESELECT;
```

2022-02-02 01:17 UTC, wilr commented on src/TagField.php
> -    public function setValue($value, $source = null)
@emteknetnz it's not removing it from the API, it's defined on the parent as public anyway.

2022-02-02 01:24 UTC, wilr commented on client/src/components/TagField.js
> +import React, { Component } from "react";
Ok, single quotes wasn't configured in the `.editorconfig` I've added that preference now.

2022-02-02 01:26 UTC, wilr commented on .editorconfig
> +quote_type = single
@emteknetnz Added the preference for single quotes

2022-06-01 08:59 UTC, wilr commented
@emteknetnz reverted readme change and rebased.

2022-06-02 02:51 UTC, emteknetnz requested changes
This does not seem to fix the original issue?  Setting `->isMultiple(false)` for both `TagField` and `StringTagfield` meant the tags did not show

Code I used for testing below:

```php
<?php
use SilverStripe\TagField\TagField;
use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\TagField\StringTagField;

class BlogPost extends SiteTree
{
    private static $many_many = [
        'BlogTags' => BlogTag::class
    ];

    private static $db = [
        'StringTags' => 'Text',
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        /** @var TagField field */
        $field = TagField::create(
            'BlogTags',
            'Blog Tags',
            BlogTag::get(),
            $this->BlogTags()
        )
            ->setShouldLazyLoad(true)
            ->setCanCreate(true)
            ->setIsMultiple(true)
            ;

        $fields->insertAfter('Title', $field);

        $field = StringTagField::create(
            'StringTags',
            'StringTags',
            ['one', 'two'],
            explode(',', $this->Tags)
        )
            ->setShouldLazyLoad(true)
            ->setIsMultiple(true)
            ;
        $fields->insertAfter('Title', $field);

        return $fields;
    }
}

<?php

use SilverStripe\ORM\DataObject;

class BlogTag extends DataObject
{
    private static $db = [
        'Title' => 'Varchar(200)',
    ];

    private static $belongs_many_many = [
        'BlogPosts' => BlogPost::class
    ];
}

<?php

use SilverStripe\Admin\ModelAdmin;

class BlogTagAdmin extends ModelAdmin
{
    private static $url_segment = 'blog-tags';

    private static $managed_models = [
        BlogTag::class
    ];
}
```

2022-06-02 02:51 UTC, emteknetnz commented on src/TagField.php
> -    public function setValue($value, $source = null)
So why are we removing it here?  Would the parent method handle different inputs of $value and $source correctly?

Parent method `MultiSelectField::setValue()` is this for reference:
```php
    public function setValue($value, $obj = null)
    {
        // If we're not passed a value directly,
        // we can look for it in a relation method on the object passed as a second arg
        if ($obj instanceof DataObject) {
            $this->loadFrom($obj);
        } else {
            parent::setValue($value);
        }
        return $this;
    }
```

2022-06-02 02:51 UTC, emteknetnz commented on tests/StringTagFieldTest.php
> +    protected function compareExpectedAndActualTags(array $expected, TagFieldTestBlogPost $record)
Why is method here?  It's not called within StringTagFieldTest?

2022-06-02 03:01 UTC, wilr commented
@emteknetnz sorry when rebasing I didn't rebuild the bundle.js so the bug would still be present. If you try that on your checkout it should be green. Just checking it out now.

2022-06-02 03:22 UTC, wilr commented on tests/StringTagFieldTest.php
> +    protected function compareExpectedAndActualTags(array $expected, TagFieldTestBlogPost $record)
Removed method.

2022-06-02 03:24 UTC, wilr commented
@emteknetnz Updated the `bundle.js` correctly now after my re-base and confirmed that example works as intended (admin:1.10.2)

2022-06-02 23:28 UTC, emteknetnz requested changes
Thanks, have tested locally, now behaves as expected

There's a failing unit test that will need to be resolved

2022-06-03 01:10 UTC, wilr commented
Failing test in Postgres was because of the fallback to `ID`. It didn't like doing `ID IN ("Test1")`.

I've removed the ID fallback now.

2022-06-06 21:49 UTC, emteknetnz requested changes
That last commit broken functionality - I manually tested that regular `TagField` no longer saves correctly when adding `->setIsMultiple(true)`.  Reverting the last commit fixes this issue, though obviously it means the postgres unit test will also fail.

2022-06-06 23:07 UTC, wilr commented
@emteknetnz fixed that regression now.

2022-06-07 01:00 UTC, emteknetnz approved these changes
Tested locally, works good

2022-06-07 01:00 UTC, merged