DEP Upgrade frontend build stack
silverstripe-labs/silverstripe-tagfield pull request #229
Opened 2023-01-18 04:13 UTC by GuySartorelli

See https://github.com/silverstripe/silverstripe-admin/pull/1389 for a wider discussion on most of the changes

## Parent issue
- https://github.com/silverstripeltd/product-issues/issues/644

2023-01-19 01:35 UTC, GuySartorelli commented
Keeping this as draft for now - once https://github.com/silverstripe/webpack-config/pull/59 is resolved this will need `yarn upgrade @silverstripe/webpack-config` to be run, and its new `yarn.lock` to be committed.

2023-01-26 02:19 UTC, GuySartorelli commented on src/TagField.php
> +        if ($this->getCanCreate() && $value) {
Without this, a new empty value entry was created.

2023-01-26 03:10 UTC, GuySartorelli commented
Webpack config changes have been tagged and included in this PR

2023-01-31 00:02 UTC, emteknetnz requested changes
CSS is wrong, it looks different from CMS 4

This PR:
![image](https://user-images.githubusercontent.com/4809037/215624295-81a61a41-0818-4135-918e-afaf7bba54d2.png)

CMS 4:
![image](https://user-images.githubusercontent.com/4809037/215624338-685a5104-b2bd-4471-8a30-1a030319e237.png)

Other issues:
- When creating a new tag, pressing 'enter' submits the form, when it should instead create the new tag
- I cannot create new tags after saving a page with tags.

2023-01-31 00:04 UTC, GuySartorelli commented
Please compare this with the tree dropdown field, not with the CMS 4 version. We went through multiple major versions of react-select and it changed a lot of the markdown and styles that came out of the box. I think some leeway for minor changes in styling is acceptable.

2023-01-31 23:53 UTC, GuySartorelli commented
> When creating a new tag, pressing 'enter' submits the form, when it should instead create the new tag

I can't reproduce this. Can you please include steps for reproduction (or just show me it happening since I sit next to you)

> I cannot create new tags after saving a page with tags.

Interesting.... I had testing this but maybe I changed something after testing it. For me, it's not that I can't create new tags specifically but I can't select multiple tags. I will resolve this.

2023-02-01 00:10 UTC, GuySartorelli commented on client/src/components/TagField.js
> +    if (!multi && passThroughAttributes.value) {
This isn't a passthrough anymore - missed this the first attempt when I pulled multi out as a distinct variable.

2023-02-01 00:53 UTC, emteknetnz commented
> Can you please include steps for reproduction

Not much beyond "add a tag and press enter" I used firefox if that makes a difference

I'll retest once I look at all the resolved PRs again

2023-02-01 21:13 UTC, emteknetnz approved these changes

2023-02-01 21:13 UTC, merged